PartsCatalog/Models/Make.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PartsCatalog.Models
{
    [Table("Makes")]
    public class Make
    {
        public const string ImagesPath = "~/Resources/Images/Makes/";

        public int Id { get; set; }

        public string Name { get; set; }

        public string Image { get; set; }

        public virtual ICollection<Model> Models { get; set; }
    }
}

PartsCatalog/Controllers/MakesController.cs
using PartsCatalog.DAL;
using PartsCatalog.Models;
using PartsCatalog.Util;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartsCatalog.Controllers
{
    public class MakesController : Controller
    {
        private IMakesRepository makesRepository;
        private IModelsRepository modelsRepository;

        public MakesController(IMakesRepository makesRepository, IModelsRepository modelsRepository)
        {
            this.makesRepository = makesRepository;
            this.modelsRepository = modelsRepository;
        }

        public ActionResult List()
        {
            return View(makesRepository.Get(orderBy: make => make.Name));
        }

        [HttpGet]
        public ActionResult Edit(int makeId)
        {
            var make = makesRepository.GetById(makeId);
            return make == null ? RedirectToAction("List") : (ActionResult) View(make);
        }

        [HttpPost]
        public ActionResult Edit(Make make, HttpPostedFileBase file)
        {
            makesRepository.SaveOrUpdate(make, file);
            TempData["Message"] = "Saved successfully";
            return RedirectToAction("Edit", new { makeId = make.Id });
        }

        public ActionResult Add()
        {
            return View("Edit", new Make());
        }

        public ActionResult Delete(int makeId)
        {
            var entity = makesRepository.GetById(makeId);
            entity.Models.ToList().ForEach(m => modelsRepository.Delete(m));
            makesRepository.Delete(entity);
            return RedirectToAction("List");
        }

    }
}

PartsCatalog/Controllers/ModelsController.cs
using PartsCatalog.DAL;
using PartsCatalog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartsCatalog.Controllers
{
    public class ModelsController : Controller
    {
        private IModelsRepository modelsRepository;
        private IMakesRepository makesRepository;

        public ModelsController(IModelsRepository modelsRepository, IMakesRepository makesRepository)
        {
            this.modelsRepository = modelsRepository;
            this.makesRepository = makesRepository;
        }

        public ActionResult List(int? makeId)
        {
            ViewBag.MakeId = makeId;
            return View(modelsRepository.GetByMakeId(makeId.Value));
        }

        [HttpGet]
        public ActionResult Edit(int makeId, int modelId)
        {
            var model = modelsRepository.GetById(modelId);
            return model == null ? RedirectToAction("List", new { makeId = makeId }) : (ActionResult)View(model);
        }

        [HttpPost]
        public ActionResult Edit(Model model, IEnumerable<HttpPostedFileBase> files)
        {
            model.Make = makesRepository.GetById(model.Make.Id);
            modelsRepository.SaveOrUpdate(model, files);
            TempData["Message"] = "Saved successfully";
            return RedirectToAction("Edit", new { makeId = model.Make.Id, modelId = model.Id });
        }

        public ActionResult Add(int? makeId)
        {
            var make = makesRepository.GetById(makeId.Value);
            return make == null ? RedirectToAction("List", "Makes") : (ActionResult)View("Edit", new Model() { Make = make });
        }

        public ActionResult Delete(int makeId, int modelId)
        {
            modelsRepository.Delete(modelId);
            return RedirectToAction("List", new { makeId = makeId });
        }
                
    }
}

PartsCatalog/Views/Makes/Edit.cshtml
@model PartsCatalog.Models.Make

@{
    ViewBag.Title = "Edit Make";
    Layout = "~/Views/LayoutPage.cshtml";
}

<div class="action-result">@TempData["Message"]</div>
@Html.ActionLink("Back", "List")
@using (Html.BeginForm("Edit", "Makes", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    <fieldset>
        @Html.HiddenFor(model => model.Id)
        <legend>Make</legend>
        <div>Name</div>
        @Html.EditorFor(model => model.Name)
        <div>Logo</div>
        @if (Model.Image != null)
        {
            <img class="make-logo-preview" src="@Url.Content(PartsCatalog.Models.Make.ImagesPath + Model.Image)" />
        }
        <p>
            <input type="file" name="file" accept="image/*" />
        </p>
        <p class="button-container">
            <input type="submit" value="Save" class="button"/>
            <input type="button" value="Delete" class="button" onclick="window.location.href='@Url.Action("Delete", new { makeId = Model.Id})';" @(Model.Id == 0 ? "disabled" : "")/>
        </p>
    </fieldset>
}

PartsCatalog/Views/Makes/List.cshtml
@model IEnumerable<PartsCatalog.Models.Make>

@{
    ViewBag.Title = "Makes";
    Layout = "~/Views/LayoutPage.cshtml";
}

<div class="makes-container">
@Html.ActionLink("Add", "Add", new { }, new { @class = "add-make" })
@foreach (var make in Model)
{
    <div class="make" onclick="window.location.href='@Url.Action("List", "Models", new { makeId = make.Id })';">
        @if (make.Image != null)
        {
            <img src="@Url.Content(PartsCatalog.Models.Make.ImagesPath + make.Image)" class="make-logo"/>
        }
        <div class="make-name">@make.Name</div>
        @Html.ActionLink("Edit", "Edit", new { makeId = make.Id }, new { @class = "edit-make" })
    </div>          
}
</div>